Randomize port of bitcoind util for integration test
Trust-Machines/core-eng pull request #171
Opened 2023-03-14 19:25 UTC by empeje

This PR aims to close the #138 by adding ways to generate random port based on available port that is exists. This is the first time I write rust, coming from C/C++ and JavaScript.

This PR itself doesn't create a meaningful changes because there's no user who invoke the `bitcoind_mine` or `bitcoind_setup` yet.

---

Closes #138

2023-03-14 23:43 UTC, empeje commented on frost-test/src/bitcoind.rs
>      let rpc = ureq::json!({"jsonrpc": "1.0", "id": "tst", "method": method, "params": params});
BITCOIND_URL in line above should incorporate the port as well

2023-03-16 22:36 UTC, donpdonp requested changes

2023-03-16 22:36 UTC, donpdonp commented on frost-test/src/bitcoind.rs
> +pub unsafe fn bitcoind_rpc(method: &str, params: impl ureq::serde::Serialize) -> serde_json::Value {
this needs a new approach without the use of `unsafe`

2023-03-16 22:36 UTC, donpdonp commented on frost-test/src/bitcoind.rs
> +    BITCOIND_URL.replace("port", &port.to_string())
if the port is left in the url as a number, it will parse into a standard library object (http::URI) where the port can be changed through methods on the uri object.

2023-03-17 19:22 UTC, empeje commented on frost-test/src/bitcoind.rs
> +    BITCOIND_URL.replace("port", &port.to_string())
@donpdonp I have udpated my approach, but I couldn't find a way to have a global mutable variable even with http:URI, so instead I'm using approach where we will generate `Config` and use it as a dependency to call the rpc. Please see the updated code if that's make sense.

2023-03-29 08:37 UTC, stjepangolemac requested changes

2023-03-29 08:37 UTC, stjepangolemac commented on frost-test/src/bitcoind.rs
> +    match ureq::post(&*get_bitcoin_url(config)).send_json(&rpc) {
It might be more idiomatic to use `get_bitcoin_url(config).as_str()`.

2023-03-29 08:37 UTC, stjepangolemac commented on frost-test/src/bitcoind.rs
> +    format!("{url}:{port}", url = BITCOIND_URL, port = config.port)
I would suggest to format this in a different way:

```
format!("{}:{}", BITCOIND_URL, config.port);
```

The reason being that rust-analyzer and clippy still have trouble properly identifying the variables if they're in the format string.

2023-03-29 08:37 UTC, stjepangolemac commented on frost-test/src/bitcoind.rs
> +fn find_port() -> u16 {
As you said you're starting out with Rust here's how this could be written in a more idiomatic way, even though it might be subjective.

```
fn find_port() -> Option<u16> {
    (18443..MAX_PORT).find(|port| port_is_available(*port))
}
```

2023-03-29 08:37 UTC, stjepangolemac commented on frost-test/src/bitcoind.rs
>      let bitcoind_child = Command::new("bitcoind")
`Command::new()` returns a `Child` that you can `kill()` so there's no need to cast to PID and use a separate function. I suppose something like this could work:

```
pub fn bitcoind_setup(config: Config) -> Child {
  ...
  ctrlc::set_handler(move || {
    child.kill().unwrap();
  });
  ...
```

2023-03-29 21:24 UTC, empeje commented
Thanks @stjepangolemac I'll update the PR :)

2023-04-05 22:22 UTC, empeje commented
Thank you for your feedback @stjepangolemac I have update everything with your feedback.

2023-04-06 06:36 UTC, stjepangolemac approved these changes

2023-04-06 06:36 UTC, stjepangolemac commented on frost-test/src/bitcoind.rs
>      let bitcoind_child = Command::new("bitcoind")
We now have both the `Child` and a PID. It seems this can be simplified to this:

```
let child = ...;
ctrlc::set_handler(move || {
  println!("kill bitcoind pid {:?}", child.id());
  child.kill();
})
```

EDIT: Actually, just realized you return PID and have it kill it on Drop. In that case maybe remove `Child` and use PID for everything? What do you think?

2023-04-06 19:30 UTC, merged