Frost-coordinator/signer: Seperate public and private components of DKG rounds for speedup
Trust-Machines/core-eng pull request #175
Opened 2023-03-15 22:58 UTC by jferrant

Builds off of @xoloki  original code to take BIP-340 compliant SchnorrProof and use it to sign a BTC tx.
As part of @xoloki recommendations, this PR splits out the public/private calculations (the generated public key can be invalid and require re-computation, so prevent wasting unnecessary time generating known invalid private keys by first ensuring the generated public key is valid)

2023-03-15 23:09 UTC, xoloki approved these changes
LGTM!  Fix the cargo and get tests passing, then feel free to squash/merge ))

2023-03-15 23:09 UTC, xoloki commented on Cargo.toml
> +wtfrost = { path = "../frost" }
Change this back to git main plz

2023-03-15 23:09 UTC, xoloki commented on frost-coordinator/src/coordinator.rs
> +        debug!("dkg_id #{}. NonceRequest sent.", self.current_dkg_id);
Glad you turned down the log spam!

2023-03-15 23:09 UTC, xoloki commented on frost-coordinator/src/coordinator.rs
> +                info!("Success: R has even y coord: {}", &R);
Maybe change this to `debug!` and the failure to `warn!`?

2023-03-15 23:09 UTC, jferrant commented on Cargo.toml
> +wtfrost = { path = "../frost" }
Will do :)

2023-03-15 23:10 UTC, jferrant commented
> LGTM! Fix the cargo and get tests passing, then feel free to squash/merge ))

uh oh. I think I need to update :P

2023-03-15 23:13 UTC, xoloki commented
> > LGTM! Fix the cargo and get tests passing, then feel free to squash/merge ))
> 
> uh oh. I think I need to update :P

Test failure is almost certainly due to cargo frost path ))

2023-03-15 23:48 UTC, xoloki requested changes

2023-03-15 23:48 UTC, xoloki commented on frost-coordinator/Cargo.toml
> +wtfrost = { git = "https://github.com/Trust-Machines/frost", branch = "main" }
This needs to be in the root, and use `workspace = true` here

2023-03-15 23:55 UTC, jferrant commented
> > > LGTM! Fix the cargo and get tests passing, then feel free to squash/merge ))
> > 
> > 
> > uh oh. I think I need to update :P
> 
> Test failure is almost certainly due to cargo frost path ))

Oh it definitely was.

2023-03-15 23:56 UTC, xoloki approved these changes
LGTM, rebase then feel free to squash/merge ))

2023-03-16 01:19 UTC, sergey-shandar approved these changes
LGTM

2023-03-16 04:31 UTC, merged