build peg-out tx
Trust-Machines/core-eng pull request #196
Opened 2023-03-24 03:08 UTC by donpdonp

copy the working peg-out builder from frost_btc test into stacks-coordinator.

2023-03-24 09:11 UTC, netrome requested changes
Cleanup request (blocking): There's some stale comments which should be cleaned up before merging.

Clarification request (not blocking): I don't see any associated issue with this PR, so it's a bit hard for me to understand the context and plan revolving this, so I have some clarifying questions about some observations on missing functionality here.

2023-03-24 09:11 UTC, netrome commented on stacks-coordinator/src/peg_wallet.rs
> +        // };
Nit: This should be cleaned up.

2023-03-24 09:11 UTC, netrome commented on stacks-coordinator/src/peg_wallet.rs
>              input: vec![peg_out_input],
We should consume a UTXO from the peg wallet to fund the peg-out fulfillment. Is there a ticket to do this?

2023-03-24 09:11 UTC, netrome commented on stacks-coordinator/src/peg_wallet.rs
>              output: vec![peg_out_output],
I guess we can't assume the input UTXOs amount to exactly what we need, so we must return the remaining balance (minus miner fee) to the peg wallet in another output.

2023-03-24 21:42 UTC, donpdonp commented on stacks-coordinator/src/peg_wallet.rs
>              input: vec![peg_out_input],
that happens earlier in the function
```
       let peg_out_input = bitcoin::TxIn {
            previous_output: utxo,
```

2023-03-24 21:49 UTC, donpdonp commented on stacks-coordinator/src/peg_wallet.rs
>              input: vec![peg_out_input],
After reading some more, this needs to be reworked. PegOutRequestOp.txid is the btc transaction of the peg-out request itself.

2023-04-19 12:57 UTC, netrome commented
Closing as this due to inactivity. The important features will find their way through @jferrant's work on the coordinator.

2023-04-19 12:57 UTC, closed without merging