WIP: Build mint transaction and set address transaction
Trust-Machines/core-eng pull request #223
Opened 2023-03-30 16:23 UTC by jferrant

2023-03-31 06:20 UTC, stjepangolemac approved these changes

2023-03-31 06:20 UTC, stjepangolemac commented on stacks-coordinator/src/stacks_transaction.rs
> +    pub fn to_blockstack_transaction(self) -> Result<BlockstackTransaction, Error> {
Maybe you're already aware but here are some breadcrumbs about serializing this tx before sending it to the network

https://github.com/stacks-network/stacks-blockchain/blob/73af120f2bc24ce2e4d0dc820956985dfe44eb88/src/chainstate/stacks/transaction.rs#L578-L593

2023-03-31 21:09 UTC, jferrant commented on stacks-coordinator/src/stacks_transaction.rs
> +    pub fn to_blockstack_transaction(self) -> Result<BlockstackTransaction, Error> {
Yeah I had tried doing that earlier, but as far as I can tell, it expects a hash representation of the tx, not the json blob. So not entirely sure if I have done it correctly, but fingers crossed. It seems to work. Just need to add some valid testing data.

2023-04-04 09:18 UTC, netrome commented on stacks-coordinator/src/make_contract_call.rs
>              nonce: None,
Not sure if this is the problem you're experiencing, but we must query the next nonce from the stacks-node and set it here.

You can get the nonce using `/v2/accounts/[Principal]`

Example response `docs/rpc/api/core-node/get-account-data.example.json`

```
{
  "balance": "0x0000000000000000000000000007a120",
  "locked": "0x0000000000000000000000000007a120",
  "unlock_height": 126,
  "nonce": 2867,
  "balance_proof": "0xabce",
  "nonce_proof": "0xabcd"
}
```

2023-04-04 17:49 UTC, sergey-shandar commented on frost-signer/src/util.rs
> +        .collect::<Vec<ecdsa::PublicKey>>()
```suggestion
        .collect()
```

2023-04-04 17:50 UTC, xoloki commented on frost-signer/src/util.rs
> +        .collect::<Vec<ecdsa::PublicKey>>()
That's my fault, I moved this code from distributed copypasta into util funds, and forgot to remove the now unnecessary generic arg to `collect`

2023-04-04 17:54 UTC, sergey-shandar commented
@jferrant don't hesitate to fix hard coded values for `make_contract_call` `left == right` tests if needed.

2023-04-04 17:59 UTC, sergey-shandar commented on frost-signer/src/util.rs
> +        .collect::<Vec<ecdsa::PublicKey>>()
Yeah, I do this all the time. BTW, I use `.collect::<Vec<_>>()` to help the Rust type interference algorithm without specifying too much.

2023-04-04 19:57 UTC, sergey-shandar commented on stacks-coordinator/src/make_contract_call.rs
> +        nonce: u64,
Could we add a new function `with_nonce` instead? I would prefer minimize a number of parameters for functions, so don't add optional parameters to the functions signature.

2023-04-05 15:34 UTC, jferrant commented
I pulled make_contract_call out entirely, but I could add it back and leave the original generic StacksTransaction as a potential route to explore? I am more in favour of the purely rust approach. I find it much easier to grok.

2023-04-05 16:17 UTC, sergey-shandar approved these changes
Awesome! No dependency on unstable and hard to debug JS code.

2023-04-05 16:24 UTC, jferrant commented
> Awesome! No dependency on unstable and hard to debug JS code.
I created https://github.com/Trust-Machines/core-eng/issues/244 to try to decouple some of this code as you suggested :)

2023-04-06 10:02 UTC, netrome requested changes
Houston we have a problem (regarding the `PegOutRequestOp`).

2023-04-06 10:02 UTC, netrome commented on stacks-coordinator/src/stacks_wallet.rs
> +        let pub_key = StacksPublicKey::recover_to_pubkey(op.txid.as_bytes(), &op.signature)
This is incorrect. The signature in the `PegOutRequestOp` signs the sha512 hash of the amount and the locking script of the peg out request transaction. I realize now that this information is not available to the coordinator... :upside_down_face: so we need to figure out how to get that information here.

Option 1: The coordinator fetches this transaction from a bitcoin node in order to retrieve the missing locking script. Ugh...
Option 2: We extend `PegOutRequestOp` in stacks-node to hold this information directly.

Thinking out loud: :thinking: 
From a security perspective both options rely on trusting information received from a running blockchain node (either Stacks or Bitcoin). Given that we'll interface with trusted nodes we host ourselves, this is fine.

I propose proceeding with Option 2. I can write up an issue for it if you think it makes sense.

2023-04-06 11:22 UTC, jferrant commented on stacks-coordinator/src/stacks_wallet.rs
> +        let pub_key = StacksPublicKey::recover_to_pubkey(op.txid.as_bytes(), &op.signature)
I am fine with Option 2. I feel like all information required to do something with a burn_op should be in the burn_op itself.

2023-04-06 12:10 UTC, jferrant commented on stacks-coordinator/src/config.rs
> +    pub network: Option<String>,
Good catch! My bad for not doing a cleanup runthrough. Was in such haste to get the darn thing done :P

2023-04-06 12:16 UTC, jferrant commented on stacks-coordinator/src/stacks_wallet.rs
>  impl StacksWallet {
I agree. Done :D

2023-04-06 13:03 UTC, netrome commented on stacks-coordinator/src/stacks_wallet.rs
> +        let pub_key = StacksPublicKey::recover_to_pubkey(op.txid.as_bytes(), &op.signature)
Issue formulated: https://github.com/stacks-network/stacks-blockchain/issues/3647 Let's leave it to the Stacks-side to derive the address of the sender (pub_key) https://github.com/stacks-network/stacks-blockchain/issues/3647

2023-04-11 16:38 UTC, jferrant commented on stacks-coordinator/src/coordinator.rs
> +            .next_nonce(self.fee_wallet().stacks().get_address())?;
@netrome is this actually correct? To always grab the nonce using the stacks wallet address?

2023-04-11 16:43 UTC, netrome commented on stacks-coordinator/src/coordinator.rs
> +            .next_nonce(self.fee_wallet().stacks().get_address())?;
I think so. We ask the stacks node for the next nonce for this particular address, which it keeps track of.

2023-04-11 16:46 UTC, soju-drinker commented on stacks-coordinator/src/coordinator.rs
> +            .next_nonce(self.fee_wallet().stacks().get_address())?;
Can we write this in a comment for future usage

2023-04-13 13:10 UTC, jferrant commented on stacks-coordinator/src/stacks_wallet.rs
> +        let pub_key = StacksPublicKey::recover_to_pubkey(op.txid.as_bytes(), &op.signature)
Pulled in the change and updated the tests :) had to update the cargo file to point to "next"

2023-04-13 13:44 UTC, netrome requested changes
Good stuff. There's a p2wpkh that I believe should be a p2tr. Please update it and I'll approve.

2023-04-13 13:44 UTC, netrome commented on stacks-coordinator/src/coordinator.rs
> +        let address = bitcoin::Address::p2wpkh(&public_key, bitcoin_network)?;
This should be a p2tr address, since we're using Schnorr signatures.

2023-04-13 14:08 UTC, jferrant commented on stacks-coordinator/src/coordinator.rs
> +        let address = bitcoin::Address::p2wpkh(&public_key, bitcoin_network)?;
There are quite a few places where I make this mistake. Will update.

2023-04-13 14:37 UTC, netrome commented on stacks-coordinator/src/peg_wallet.rs
> +    fn get_address(&self) -> &BitcoinAddress;
@jferrant any opinions?

2023-04-13 14:37 UTC, netrome commented on stacks-coordinator/src/coordinator.rs
> +        let address = bitcoin::Address::p2wpkh(&public_key, bitcoin_network)?;
I see this is resolved now :heavy_check_mark:

2023-04-13 16:27 UTC, jferrant commented on stacks-coordinator/src/peg_wallet.rs
> +    fn get_address(&self) -> &BitcoinAddress;
I have no opinion for or against :) will change.

2023-04-13 16:38 UTC, jferrant commented
> I think you missed my nit comment about `get_address`. It's not a blocker for merging though.

I saw, but I did forget :P Addressed now (no pun intended...)

2023-04-13 16:46 UTC, merged