Sign and frost messages
Trust-Machines/core-eng pull request #238
Opened 2023-03-31 19:26 UTC by xoloki

Since all `FROST` communication takes place over broadcast channels, it is necessary for `frost-signer` and `frost-coordinator` to be able to verify that messages have arrived unaltered, and come from the purported signer.  

We previously added `ECDSA` signature support to `p256k1`.  Add signature fields to all `FROST` network messages, config support to hold private keys for the agent in question, and public keys for all `signers` and the `coordinator`.

2023-04-02 01:18 UTC, jferrant commented on frost-coordinator/src/coordinator.rs
> +                            assert!(msg.verify(&m.sig, &signer_public_keys[msg.signer_id - 1]))
I think you can condense some of these matches using something like the following (If this was done intentionally to make future changes easier, no worries..but would make it a bit easier to grok I think.):
```
MessageTypes::DkgBegin(msg) | MessageTypes::DkgPrivateBegin(msg) => {
   assert!(msg_verify(&m.sig, &coordinator_public_key))
}
```

2023-04-02 01:22 UTC, jferrant commented on frost-signer/src/signer.rs
> +        let signer_public_keys = self
This seems to come up quite a bit. Might be worth while making this into a helper function for parsing a vector public keys.

2023-04-02 01:28 UTC, xoloki commented on frost-coordinator/src/coordinator.rs
> +                            assert!(msg.verify(&m.sig, &signer_public_keys[msg.signer_id - 1]))
Good point, that should be a lot less verbose.  I'll do that now.

2023-04-02 01:34 UTC, jferrant commented on frost-signer/src/signer.rs
> +                            msg.sign(&ecdsa_private_key).expect("").to_vec()
Similar to above, all of these could be combined if desired.

2023-04-02 01:38 UTC, xoloki commented on frost-signer/src/signer.rs
> +                            msg.sign(&ecdsa_private_key).expect("").to_vec()
I got all excited, thinking it would work for basically all the msg types that had similar fields.  Unfortunately, it only works if the actual wrapped msg type is the same :(

Fixed everything I could in both places.

2023-04-02 01:41 UTC, jferrant commented on frost-signer/src/signer.rs
> +                            msg.sign(&ecdsa_private_key).expect("").to_vec()
Yeah I only noticed this when I opened in visual studio and saw that they are all different msg types :( maybe in future we can combine some of them (might not need to be separate types if the wrapping in enum gives enough context but prob not. Can investigate later)

2023-04-02 01:44 UTC, xoloki commented on frost-signer/src/signer.rs
> +        let signer_public_keys = self
I have it in both `frost-signer` and `frost-coordinator`, do you think putting it in `frost-signer/src/lib.rs` is a reasonable place?  Or should I make like a `util.rs` mod?

2023-04-02 01:45 UTC, jferrant commented on frost-signer/tests/net.rs
> +        sig: [0u8; 64].to_vec(),
Not sure you share Sergey's annoyance at macros, but you could replace this with the more rusty vec![0; 64] if you want to :P

2023-04-02 01:46 UTC, jferrant commented on stacks-signer/src/main.rs
> +                panic!("An error occurred reading config file {}: {}", config, e);
Nit: To be consistent, might want to make this a warn. Or change the warn above to a panic!

2023-04-02 01:47 UTC, xoloki commented on frost-signer/tests/net.rs
> +        sig: [0u8; 64].to_vec(),
Done.

2023-04-02 01:48 UTC, jferrant commented on frost-signer/src/signer.rs
> +        let signer_public_keys = self
I think in general I prefer having util.rs files to be extra explicit. However, if you don't anticipate a lot more helper functions, not against it being in lib.rs

2023-04-02 01:49 UTC, jferrant approved these changes
Only the nits. LGTM :)

2023-04-02 01:59 UTC, xoloki commented on frost-signer/src/signer.rs
> +        let signer_public_keys = self
Done.

2023-04-02 02:01 UTC, xoloki commented on stacks-signer/src/main.rs
> +                panic!("An error occurred reading config file {}: {}", config, e);
Yeah if main fails that's a `panic` not a `warn`.

Fixed.

2023-04-02 04:47 UTC, igorsyl requested changes
![image](https://user-images.githubusercontent.com/1248500/229331894-c9615a49-724a-4c0f-bf6b-2086d7de1e47.png)

2023-04-02 04:47 UTC, igorsyl commented on Cargo.toml
> +sha2 = "0.10"
Why are we downgrading sha3 to sha2?

2023-04-02 04:47 UTC, igorsyl commented on frost-coordinator/src/coordinator.rs
> +    ecdsa_private_key: Scalar,
Are we able to use Schnorr over ECDSA for packet signatures? If not, why not?

2023-04-02 04:47 UTC, igorsyl commented on frost-coordinator/src/coordinator.rs
> +    signer_public_keys: Vec<String>,
Can we create a semantic type PublicKey=String to help the reader?

2023-04-02 04:47 UTC, igorsyl commented on frost-coordinator/src/coordinator.rs
> +        let ecdsa_private_key = Scalar::try_from(config.ecdsa_private_key.as_str())
Instead of calling the config `ecdsa_private_key` which encodes the sig type, can we call it something like `network_private_key` which encodes the purpose?

2023-04-02 04:47 UTC, igorsyl commented on frost-signer/conf/signer.toml
> +ecdsa_private_key = "9aSCCR6eirt1NAHwJtSz4HMwBHTyMo62SyPMvVDt5DQn"
Could we also set these using environment variables?

2023-04-02 04:47 UTC, igorsyl commented on frost-signer/src/signer.rs
>          net.poll(id);
Does this use epoll under the hood?

2023-04-02 04:47 UTC, igorsyl commented on frost-signer/src/signing_round.rs
> +        hasher.update(self.dkg_id.to_be_bytes());
Is it common practice to add a prefix string to avoid potential sig attacks?

2023-04-02 04:49 UTC, xoloki commented on Cargo.toml
> +sha2 = "0.10"
Because we need to use sha2 for bitcoin compatibility, and if we have to use it anyway might as well use it everywhere.

2023-04-02 04:52 UTC, xoloki commented on frost-coordinator/src/coordinator.rs
> +    ecdsa_private_key: Scalar,
We certainly could use Schnorr, but it doesn't really seem to gain us anything.  We get a fast ECDSA implementation from a secp256k1, and we aren't aggregating or verifying in parallel, which are the reasons to use Schnorr.

2023-04-02 04:54 UTC, xoloki commented on frost-coordinator/src/coordinator.rs
> +    signer_public_keys: Vec<String>,
`String` is how it's stored in the config file, it's not indicative of anything semantic about the type.

2023-04-02 04:55 UTC, xoloki commented on frost-coordinator/src/coordinator.rs
> +        let ecdsa_private_key = Scalar::try_from(config.ecdsa_private_key.as_str())
Sure. We could also just call it private key, it's the only private key we're storing.

2023-04-02 04:55 UTC, xoloki commented on frost-signer/conf/signer.toml
> +ecdsa_private_key = "9aSCCR6eirt1NAHwJtSz4HMwBHTyMo62SyPMvVDt5DQn"
We certainly could.  This PR is big enough already, so I'd prefer to save it for a follow-on.

2023-04-02 04:56 UTC, xoloki commented on frost-signer/src/signer.rs
>          net.poll(id);
No idea what's going on under the hood.  @sergey-shandar ?

2023-04-02 04:57 UTC, xoloki commented on frost-signer/src/signing_round.rs
> +        hasher.update(self.dkg_id.to_be_bytes());
Yeah, I can definitely add prefix strings.

2023-04-02 04:57 UTC, xoloki commented on frost-signer/src/signing_round.rs
> +        hasher.update(self.dkg_id.to_be_bytes());
In fact, for `DkgQuery` the prefix string is the only thing we're hashing XD

2023-04-02 05:08 UTC, xoloki commented on frost-coordinator/src/coordinator.rs
> +        let ecdsa_private_key = Scalar::try_from(config.ecdsa_private_key.as_str())
Done, `network_private_key` it is.

2023-04-02 05:08 UTC, xoloki commented on frost-signer/src/signing_round.rs
> +        hasher.update(self.dkg_id.to_be_bytes());
Done.

2023-04-02 05:20 UTC, xoloki commented on frost-signer/src/signer.rs
>          net.poll(id);
Semantically, the token `poll` here means repeatedly hitting the same endpoint until you get something you want.  Not like linux's `poll` or `epoll`, which are functionally doing a `select` not a semantic `poll`.

I really really hope the `stacks-node` version of this operates as a long poll, i.e. doesn't return until you get what you asked for.  Distributed-systems me *hates* polling :P

2023-04-02 05:33 UTC, igorsyl commented on Cargo.toml
> +sha2 = "0.10"
Can we use sha3 for network stuff and sha2 for bitcoin stuff?

2023-04-02 05:34 UTC, igorsyl commented on frost-coordinator/src/coordinator.rs
> +    signer_public_keys: Vec<String>,
Yes, but we can use a type alias to indicate that it's not any string but a pubkey string.

2023-04-02 05:36 UTC, igorsyl approved these changes
Approving to unblock. We should do a whole-repo review every now and then.

2023-04-02 05:37 UTC, igorsyl commented on frost-signer/src/signing_round.rs
> +        hasher.update(self.dkg_id.to_be_bytes());
Several other hashing functions as well. Didn't tag them all.

2023-04-02 05:37 UTC, igorsyl commented on frost-signer/conf/signer.toml
> +ecdsa_private_key = "9aSCCR6eirt1NAHwJtSz4HMwBHTyMo62SyPMvVDt5DQn"
I'll need it for deployment. Thanks!

2023-04-02 05:40 UTC, xoloki commented on Cargo.toml
> +sha2 = "0.10"
Sure, let's save it for the follow on

2023-04-02 05:40 UTC, xoloki commented on frost-signer/src/signing_round.rs
> +        hasher.update(self.dkg_id.to_be_bytes());
Refresh, latest code should have them all.

2023-04-02 05:43 UTC, xoloki commented on frost-signer/conf/signer.toml
> +ecdsa_private_key = "9aSCCR6eirt1NAHwJtSz4HMwBHTyMo62SyPMvVDt5DQn"
It's there, refresh XD

2023-04-02 05:44 UTC, merged

2023-08-08 14:17 UTC, dreadful-dev commented on frost-coordinator/src/coordinator.rs
> +    ecdsa_private_key: Scalar,
Like so:
```mermaid
graph TB
	subgraph Z["Papaya"]
		direction TB;
		C-->|DKG+Signing|B[sBTC Relay]
	    	C[Papaya coordinator]-->|Set protocol disbursement address|D[Papaya Stacking Contract]
	    	C-->|Get signer configuration|D
	    	C-->|DKG+Signing|P[Papaya Relay]
		S[Signer]-->|DKG+Signing|P
	end
	subgraph ZA["sBTC"]
		direction TB;
		G[Stacks coordinator]-->|Mint/burn sBTC|H[sBTC contract]
		G-->|Set peg wallet address|H
		G-->|Get signer configuration|H
		G-->|Get sBTC ops|N[Stacks node RPC]
		G-->|DKG+Signing|Q[Relay]
		S1[Signer]-->|DKG+Signing|Q
	end
	C-->|DKG+Signing|Q

```