Clarity/clarity bitcoin segwit
Trust-Machines/core-eng pull request #304
Opened 2023-04-27 19:49 UTC by FriendsFerdinand

adding segwit parsing to the clarity-bitcoin contract

2023-04-30 22:54 UTC, MarvinJanssen requested changes
Awesome! Nice .clar test file too.

2023-04-30 22:54 UTC, MarvinJanssen commented on sbtc-mini/tests/clarity-bitcoin_test.clar
Could you provide a human-readable representation of these test vectors?

2023-04-30 22:54 UTC, MarvinJanssen commented on sbtc-mini/contracts/clarity-bitcoin.clar
>  	(cproof (list 14 (buff 32))) ;; merkle proof for coinbase tx
Why were these two parameters added? Can it not be extracted from the Coinbase tx `wtx`?

2023-04-30 22:56 UTC, FriendsFerdinand commented on sbtc-mini/contracts/clarity-bitcoin.clar
>  	(cproof (list 14 (buff 32))) ;; merkle proof for coinbase tx
No because they are hashed before being inserted in the commitment output (see line 459)

2023-05-08 21:21 UTC, MarvinJanssen commented on sbtc-mini/contracts/clarity-bitcoin.clar
> +)
We should create a mock burn block header registry so that we can make tests more true to life.

Something like:

```clarity
(define-map mock-burnchain-header-hashes uint (buff 32))

(define-public (mock-add-burnchain-block-header-hash (burn-height uint) (hash (buff 32)))
 (ok (map-set mock-burnchain-header-hashes burn-height hash))
)

(define-read-only (get-bc-h-hash (bh uint))
   (if DEBUG-MODE (map-get? mock-burnchain-header-hashes bh) (get-burn-block-info? header-hash bh))
```

2023-05-15 23:31 UTC, jo-tm commented
@FriendsFerdinand marvin requested some changes on this PR, please merge with or without changes, so we can have smaller PRs in time and #commits.

2023-05-16 15:54 UTC, FriendsFerdinand commented
@jo-tm review is required.

2023-05-20 00:23 UTC, jo-tm requested changes
Requested minor changes on commented code.

2023-05-20 00:23 UTC, jo-tm commented on sbtc-mini/contracts/clarity-bitcoin.clar
> +;; Helper functions for smart contract that want to use information of a Bitcoin transaction
Can we remove this commented code @FriendsFerdinand ? Maybe you can move it into an issue on backlog?

2023-05-21 21:00 UTC, FriendsFerdinand commented on sbtc-mini/contracts/clarity-bitcoin.clar
> +;; Helper functions for smart contract that want to use information of a Bitcoin transaction
It's not commented code, it describes the function's output. You raised a good point and I forgot to update this to reflect segwit transactions.

2023-05-23 13:42 UTC, jo-tm commented on sbtc-mini/contracts/clarity-bitcoin.clar
> +;; Helper functions for smart contract that want to use information of a Bitcoin transaction
excellent

2023-05-23 13:43 UTC, jo-tm commented
approved on my side, @friedger @MarvinJanssen  @setzeus  can you please review or comment.

2023-05-30 04:58 UTC, MarvinJanssen approved these changes
Looks good to me. There are various points where we can do runtime cost optimisations, but I think that is best done in future PRs. With this merged we have a base that we can build on.

2023-05-30 04:58 UTC, MarvinJanssen commented on sbtc-mini/contracts/clarity-bitcoin.clar
>  	(cproof (list 14 (buff 32))) ;; merkle proof for coinbase tx
I guess for now my only comment is what I mentioned on the call. We can get rid of the list because the Coinbase transaction is always the first, so we only need to provide the right leaf hash.

2023-05-30 21:04 UTC, FriendsFerdinand commented on sbtc-mini/contracts/clarity-bitcoin.clar
>  	(cproof (list 14 (buff 32))) ;; merkle proof for coinbase tx
We can't get rid of the list, we still need to hash our way to the leaf at position 0:
```
                   [Root]
                    /    \
             [Hash A]   [Hash B]
              /   \        /   \
       [Hash A1] [Hash A2] [Hash B1] [Hash B2]
       /  \        /  \          /   \         /  \
    [L1] [L2]    [L3] [L4]     [L5] [L6]      [L7] [L8]
```

(B, A2, L2)

so we know we hash left left left, but that's all we can optimize for

2023-06-06 16:27 UTC, MarvinJanssen commented on sbtc-mini/contracts/clarity-bitcoin.clar
>  	(cproof (list 14 (buff 32))) ;; merkle proof for coinbase tx
Ah you're right what was I thinking. First in the list obviously does not mean the first leaf.

2023-06-06 22:17 UTC, merged