WIP: Add contract calls to get config options
Trust-Machines/core-eng pull request #324
Opened 2023-05-08 04:08 UTC by jferrant

2023-05-08 13:06 UTC, stjepangolemac reviewed
Didn't find anything suspicious on first glance. Will make sure to review once more when it's ready.

2023-05-08 13:06 UTC, stjepangolemac commented on stacks-coordinator/src/stacks_wallet.rs
> +            &vec![pk],
It might not need `vec!` here if it expects a slice.

2023-05-08 13:31 UTC, netrome reviewed
Some nits and style thoughts along the way. Let me know when the final PR is ready and I'll re-review.

2023-05-08 18:40 UTC, jferrant commented on stacks-coordinator/src/stacks_wallet.rs
> +            &vec![pk],
It requires a &Vec<T> :/

2023-05-08 22:20 UTC, xoloki requested changes
One question for now, will review more thoroughly after the PR is out of draft.

2023-05-08 22:20 UTC, xoloki commented on stacks-coordinator/conf/coordinator.toml
> +sbtc_contract = "ST3N4AJFZZYC4BK99H53XP8KDGXFGQ2PRSPNET8TN.sky-blue-elephant"
Does this point to your recent contract PR's deployment?  If so, can you change it back now that's it's been merged?

2023-05-09 13:16 UTC, netrome commented on stacks-coordinator/src/stacks_node/client.rs
> +                    let value = tuple_data
Ah I missed that. But you can include the struct in the match statement. Something like:
```
if let ClarityValue::Optional(OptionalData{data: Some(ClarityValue::Tuple(tuple_data)), ..}) = ...
```

2023-05-09 15:46 UTC, netrome commented on stacks-coordinator/src/stacks_node/client.rs
> +                    let value = tuple_data
Yeah that seems to be unstable https://doc.rust-lang.org/beta/unstable-book/language-features/box-patterns.html

2023-05-16 07:32 UTC, netrome approved these changes
LGTM. Just some redundant `thread::sleep` in tests calls I'd like to see removed.

2023-05-16 07:32 UTC, netrome commented on stacks-coordinator/src/stacks_node/client.rs
> +            sleep(Duration::from_millis(100));
```suggestion
```

2023-05-16 07:32 UTC, netrome commented on stacks-coordinator/src/stacks_node/client.rs
> +            sleep(Duration::from_millis(100));
```suggestion
```

2023-05-16 07:32 UTC, netrome commented on stacks-coordinator/src/stacks_node/client.rs
> +            sleep(Duration::from_millis(100));
```suggestion
```

2023-05-16 07:32 UTC, netrome commented on stacks-coordinator/src/stacks_node/client.rs
> +            sleep(Duration::from_millis(100));
```suggestion
```

2023-05-16 07:32 UTC, netrome commented on stacks-coordinator/src/stacks_node/client.rs
> +            sleep(Duration::from_millis(100));
```suggestion
```

2023-05-16 07:32 UTC, netrome commented on stacks-coordinator/src/stacks_node/client.rs
> +            sleep(Duration::from_millis(100));
```suggestion
```

2023-05-16 07:32 UTC, netrome commented on stacks-coordinator/src/stacks_node/client.rs
> +            sleep(Duration::from_millis(100));
```suggestion
```

2023-05-16 14:03 UTC, jferrant commented
> 

Good catch. This was a "copy/paste without thinking" moment

2023-05-18 13:33 UTC, stjepangolemac approved these changes

2023-05-25 17:12 UTC, merged