feat(test-vectors): refactor draft
Trust-Machines/core-eng pull request #334
Opened 2023-05-10 13:27 UTC by soju-drinker

2023-05-10 19:30 UTC, netrome commented on test-vectors/src/lib.rs
> +mod utils;
fix: These modules should be public to expose the functions
```suggestion
pub mod peg_handoff;
pub mod peg_in;
pub mod peg_out;
pub mod utils;
```

2023-05-10 21:45 UTC, MarvinJanssen commented
Can the generated test vectors be checked into the repo for easy access? For example hex-encoded in the `README.md`?

2023-05-11 07:54 UTC, netrome requested changes
Nice stuff. Just fix the u8->u64 and omit "request" from the peg in function and we're good to go.

2023-05-11 07:54 UTC, netrome commented on test-vectors/src/peg_handoff.rs
> +        .push_slice::<[u8; 1]>([reward_cycle])
Nice with the explicit slice size annotations :star:

2023-05-11 07:54 UTC, netrome commented on test-vectors/src/peg_handoff.rs
> +        .push_slice::<[u8; 1]>([reward_cycle])
The reward cycle should be a u64 though.
```suggestion
        .push_slice::<[u8; 3]>(op_bytes)
        .push_slice(reward_cycle.as_be_bytes())
```

2023-05-11 07:54 UTC, netrome commented on test-vectors/src/peg_handoff.rs
> +fn generate_peg_handoff_output(peg_wallet_address: [u8; 32], reward_cycle: u8) -> Vec<TxOut> {
```suggestion
fn generate_peg_handoff_output(peg_wallet_address: [u8; 32], reward_cycle: u64) -> Vec<TxOut> {
```

2023-05-11 07:54 UTC, netrome commented on test-vectors/src/peg_handoff.rs
> +        .push_slice::<[u8; 1]>([reward_cycle])
The reward cycle should be a u64 though.
```suggestion
        .push_slice::<[u8; 3]>(op_bytes)
        .push_slice(reward_cycle.as_be_bytes())
```

2023-05-11 07:54 UTC, netrome commented on test-vectors/src/peg_in.rs
> +        sequence: Sequence(65535),
```suggestion
        sequence: Sequence::MAX,
```

2023-05-11 07:54 UTC, netrome commented on test-vectors/src/peg_in.rs
> +fn generate_peg_in_request_output(
The peg in operation is not a request in the current design.
```suggestion
fn generate_peg_in_output(
```

2023-05-11 07:54 UTC, netrome commented on test-vectors/src/peg_in.rs
> +    stacks_add: [u8; 20],
I don't see any point in abbreviating this name
```suggestion
    stacks_address: [u8; 20],
```

2023-05-11 07:54 UTC, netrome commented on test-vectors/src/utils.rs
> +use bitcoin::{consensus::encode::serialize, Transaction, TxIn, TxOut};
Nit: From a code organization perspective I think this should be a private module. However, I assume the `serialize_tx` function is external so it should either be publicly re-exported or implemented somewhere else.

2023-05-11 19:35 UTC, soju-drinker commented on test-vectors/src/utils.rs
> +use bitcoin::{consensus::encode::serialize, Transaction, TxIn, TxOut};
Yeah I agree with that

2023-05-11 20:22 UTC, jferrant approved these changes
LGTM :D

2023-05-12 07:51 UTC, netrome commented on test-vectors/src/peg_in.rs
> +        .push_slice::<[u8; 20]>(stacks_address)
I forgot the version byte when we last talked about this. The version byte should be encoded in the bytes. Can you add a version byte with version 26 encoded as a single leading byte to the stacks address?

Why 26? It's the constant `C32_ADDRESS_VERSION_TESTNET_SINGLESIG` defined in `stacks-common/src/address/mod.rs`

2023-05-12 11:17 UTC, soju-drinker commented on test-vectors/src/peg_in.rs
> +        .push_slice::<[u8; 20]>(stacks_address)
Sure! Just curious, so this version is going to be different on mainnet?

2023-05-12 11:31 UTC, netrome commented on test-vectors/src/peg_in.rs
> +        .push_slice::<[u8; 20]>(stacks_address)
Yep, it will.

2023-05-12 11:50 UTC, netrome approved these changes

2023-05-12 12:41 UTC, merged