feat: Initial stab at stacks-signer design
Trust-Machines/core-eng pull request #38
Opened 2023-02-08 14:52 UTC by netrome

This design is not super compatible with the current version of frost-signer. Ideas for how to bring these two closer are much appreciated.

2023-02-08 17:43 UTC, xoloki approved these changes
LGTM

2023-02-08 22:40 UTC, donpdonp commented on stacks-signer/README.md
> +    C --> D[Send shares]
```suggestion
    C --> D[Send shares]
```

2023-02-08 22:40 UTC, donpdonp approved these changes

2023-02-09 00:09 UTC, igorsyl commented on stacks-signer/README.md
> +The signer interacts with th sBTC contract to read public keys for other signers
"th sBTC"

2023-02-09 00:10 UTC, igorsyl commented on stacks-signer/README.md
> +pub trait NetworkedSigner {
SignerService?

2023-02-09 00:10 UTC, igorsyl commented on stacks-signer/README.md
> +    type StacksNode; // Shared implementation with frost-coordinator
... with _stacks_-coordinator?

2023-02-09 00:12 UTC, igorsyl commented on stacks-signer/README.md
> +pub trait Signer {
These methods need to be aware of the `round_id`.

2023-02-09 00:14 UTC, igorsyl requested changes
This is great! The design of the db storing the private keys is important. Ideally, we would an append-only db to avoid risk of deleting keys.

2023-02-09 10:09 UTC, netrome commented on stacks-signer/README.md
> +The signer interacts with th sBTC contract to read public keys for other signers
Wha? Ca't yo fil i th missin lettrs whn readin

2023-02-09 10:09 UTC, netrome commented on stacks-signer/README.md
> +pub trait NetworkedSigner {
Yeah that's better!

2023-02-09 10:10 UTC, netrome commented on stacks-signer/README.md
> +    type StacksNode; // Shared implementation with frost-coordinator
Correct!

2023-02-09 10:14 UTC, netrome commented on stacks-signer/README.md
> +    type StacksNode; // Shared implementation with frost-coordinator
Updated.

2023-02-09 10:15 UTC, netrome commented on stacks-signer/README.md
> +pub trait NetworkedSigner {
Updated.

2023-02-09 10:15 UTC, netrome commented on stacks-signer/README.md
> +    C --> D[Send shares]
Updated :heavy_check_mark:

2023-02-09 10:16 UTC, netrome commented on stacks-signer/README.md
> +pub trait Signer {
Good point, updated.

2023-02-09 15:27 UTC, merged

2023-02-09 17:44 UTC, xoloki commented on stacks-signer/README.md
> +The signer interacts with th sBTC contract to read public keys for other signers
It's a curious aspect of the human language ability, but it's possible in many languages to leave the vowels out and still be fully intelligible.  Some languages like Hebrew don't even have glyphs for vowels, they use diacritics which are optional.

2023-02-10 08:40 UTC, netrome commented on stacks-signer/README.md
> +The signer interacts with th sBTC contract to read public keys for other signers
Indeed, while other languages like Japanese and Finnish are completely phonetic. And then we have English... where the grapheme to phoneme correlation is at that sweet spot where you motivated to guess how new words should be pronounced, but you're almost always wrong.