Use `wtfrost` instead of `frost`.
Trust-Machines/core-eng pull request #46
Opened 2023-02-09 20:35 UTC by sergey-shandar

2023-02-09 20:37 UTC, xoloki requested changes
One small change, otherwise LGTM

2023-02-09 20:37 UTC, xoloki commented on frost-test/Cargo.toml
> +wtfrost = { workspace = true }
no newline at end of file

2023-02-09 20:54 UTC, xoloki approved these changes
LGTM

2023-02-10 01:05 UTC, igorsyl approved these changes

2023-02-10 05:02 UTC, merged