Signer sign
Trust-Machines/core-eng pull request #48
Opened 2023-02-10 03:34 UTC by donpdonp

Implements #6  in signer and coordinator:

NonceRequest/NonceResponse 

SignatureShareRequest/SignatureShareResponse

goal: signed message

in separate terminals run:
```
relay-server $ cargo run
frost-signer $ cargo run -- --id 3
frost-signer $ cargo run -- --id 2
frost-signer $ cargo run -- --id 1
frost-coordinator $ cargo run dkg-sign -- 1 2 3 4

```

2023-02-10 04:20 UTC, xoloki requested changes
Couple of changes and comments.  I'll try this branch when I get back to my computer and test some more

2023-02-10 04:20 UTC, xoloki commented on frost-coordinator/src/coordinator.rs
> +    pub fn sign_message(&mut self, msg: &[u8]) -> Result<(), Error> {
Should `sign_message` return the group signature?

2023-02-10 04:20 UTC, xoloki commented on frost-coordinator/src/coordinator.rs
> +            if self.public_nonces.len() == self.threshold {
The way v1 signer works, it signs for all parties, not just the ones in the signing set.  So if you short circuit this way you will get more party sigs than you want, and will need to discard the ones not in the signing set

2023-02-10 05:44 UTC, igorsyl commented
@donpdonp I resolved the conflicts. Feel free to pop off the merge commit if it's broken.

2023-02-10 17:08 UTC, donpdonp commented on frost-coordinator/src/coordinator.rs
> +            if self.public_nonces.len() == self.threshold {
That line is a fmt change. Its from the original branch, but its good to know more about the requirements of sign_message.

https://github.com/Trust-Machines/core-eng/blob/coordinator-aggregate-key/frost-coordinator/src/coordinator.rs#L126

2023-02-11 06:10 UTC, xoloki approved these changes
LGTM.  There's still one small thing, we are waiting for nonces from all parties before trying to sign.  This is because `v1::Signer` will return party sigs from all parties.  We can probably fix this with a little munging on either `frost-signer` or `frost-coordinator`, but I think this PR can go in as is.

2023-02-13 05:28 UTC, igorsyl approved these changes
lgtm

2023-02-13 05:44 UTC, merged