frost btc integration test design doc
Trust-Machines/core-eng pull request #67
Opened 2023-02-15 19:05 UTC by donpdonp

`docs/frost-btc.md` contains the design

2023-02-15 19:08 UTC, donpdonp commented
the design is committed to the branch instead of a comment on the PR or issue #65.

link for easier reference as the Files Changed view doesnt render markdown.
https://github.com/Trust-Machines/core-eng/blob/test-frost-btc/frost-test/docs/frost-btc.md

I'm not sure which is preferable, putting such a design doc in the PR or as a file in the branch itself. A github PR comment is easier to view, but it also get lost easily once the PR is closed.

2023-02-16 05:47 UTC, igorsyl commented
Thank you for writing up this clear design doc @donpdonp 
We definitely want to keep the docs in our repo so I support the way you've structured this PR!

2023-02-16 09:05 UTC, netrome requested changes
Mostly looks good to me. The only missing piece I see is the step where the peg-out request is made.

2023-02-16 09:05 UTC, netrome commented on frost-test/docs/frost-btc.md
> +activity.
Does this imply we should expose a more fine-grained control over the `stacks-coordinator` functionality in its public interface rather than just the ability to start/stop the main event loop?

2023-02-16 09:05 UTC, netrome commented on frost-test/docs/frost-btc.md
> +* coordinator publishes BTC TX
This seems like the peg-out fulfillment flow. We should add a step where the user generates a BTC TX to request pegging out.

2023-02-16 10:46 UTC, stjepangolemac commented on frost-test/docs/frost-btc.md
> +activity.
If we do need to expose more control over it something like this could work:

1. Extract internal loop logic from `run()` into `run_once()`
2. Repeatedly call `run_once()` from the `run()` loop

With a note that `run_once()` shouldn't take self by value so the coordinator can be used or modified after it's called.

2023-02-16 10:55 UTC, netrome commented on frost-test/docs/frost-btc.md
> +activity.
Sounds like a viable approach, there's no reason to take ownership of self in the current run loop either. It's a pattern I typically apply when a struct corresponds to the state of a thread or async task, to mark that the task handle is the main point of interaction with the event loop.

2023-02-16 22:21 UTC, donpdonp commented on frost-test/docs/frost-btc.md
> +activity.
exactly - i expect this test will be most of the code in main() for signer and coordinator. I made an initial attempt and coordinator has two or three main-loops waiting on network activity. If it is dissected into functions that run to completion immediately, and keep the networking loops in main() then that seems maximally testable.

I took a shortcut and tried to put the signer and coordinator (and now the relay-server) into its own thread and using http://localhost for communication. That has made more progress.

2023-02-17 00:37 UTC, donpdonp commented on frost-test/docs/frost-btc.md
> +* coordinator publishes BTC TX
Done

2023-02-17 07:27 UTC, igorsyl commented
Sorry to chime in late here. I propose we complete this issue in two steps:

1. Use frost + rust-bitcoin crates **only** (no core-eng repo) for dkg, and bitcoin transaction signing. This is the minimal proof of concept. I refer to this as frost-**lib** + bitcoin. Knowing how to accomplish this is in the critical path for the Alpha release.

3. Write an end-to-end example using the networking protocol available in core-eng repository. I refer to this as frost-**net** + bitcoin. Arguably, this test is not on the critical path for Alpha so let's create a second child issue and pause and prioritize for next milestone.

2023-02-17 10:53 UTC, netrome commented on frost-test/docs/frost-btc.md
> +activity.
Cool, sounds good! I'll create an issue to update this in `stacks-coordinator` then.

2023-02-17 10:59 UTC, netrome commented on frost-test/docs/frost-btc.md
> +activity.
Created this issue: https://github.com/Trust-Machines/core-eng/issues/73

2023-02-17 11:06 UTC, netrome approved these changes
lgtm, I created https://github.com/Trust-Machines/core-eng/issues/73 to update the stacks-coordinator event loop as proposed here.

2023-02-19 13:27 UTC, igorsyl commented
@donpdonp you can use this link to view the doc nicely :)

https://github.com/Trust-Machines/core-eng/pull/67/files#diff-d21335a24962c8b56e9d71517844a5ddd0605530ac0854a423c7eb38b583ee61

2023-02-28 11:04 UTC, stjepangolemac approved these changes

2023-02-28 13:50 UTC, igorsyl commented on frost-test/docs/frost-btc.md
> +
@donpdonp Let's add the learnings and a detailed write-up of Schnorr's signature BIP-340 encoding.

2023-03-01 01:52 UTC, donpdonp commented on frost-test/docs/frost-btc.md
> +
I added a note about BIP340's "X only" pubkey. A more complete write-up needs more investigation into how this affects FROST. I'll merge this much and update it again later if necessary.

2023-03-01 02:02 UTC, merged

2023-03-01 02:13 UTC, igorsyl commented on frost-test/docs/frost-btc.md
> +* Why P2TR(Taproot)? The process depends on FROST which generates a Schnorr signtaure. Only a Taproot output (segwit v1) can be spent by an input with a Schnorr signture.
Link to bitcoin source code line would be great!

2023-03-01 02:31 UTC, donpdonp commented on frost-test/docs/frost-btc.md
> +* Why P2TR(Taproot)? The process depends on FROST which generates a Schnorr signtaure. Only a Taproot output (segwit v1) can be spent by an input with a Schnorr signture.
Here is the bitcoin code
https://github.com/bitcoin/bitcoin/blob/master/src/script/interpreter.cpp#L391
```cpp
    case SigVersion::WITNESS_V0:
        return EvalChecksigPreTapscript(sig, pubkey, pbegincodehash, pend, flags, checker, sigversion, serror, success);
    case SigVersion::TAPSCRIPT:
        return EvalChecksigTapscript(sig, pubkey, execdata, flags, checker, sigversion, serror, success);
```
 `EvalChecksigTapscript` is one of the only places `CheckSchnorrSignature` gets used. The path for WITNESS_V0 does not.

2023-03-01 02:33 UTC, igorsyl commented on frost-test/docs/frost-btc.md
> +* Why P2TR(Taproot)? The process depends on FROST which generates a Schnorr signtaure. Only a Taproot output (segwit v1) can be spent by an input with a Schnorr signture.
Make sure you use a permalink. Otherwise, the link may go stale if it references to a tag.