stacks-js-rs: Serialize fee wallet commands.
Trust-Machines/core-eng pull request #76
Opened 2023-02-17 21:40 UTC by sergey-shandar

2023-02-20 10:03 UTC, netrome requested changes
Overall looks good to me, but I'd request to reduce the amount of data we serialize and send to JS before merging this.

2023-02-20 10:03 UTC, netrome commented on stacks-js-rs/tests/rpc.rs
> +        let result = js.call::<_, Value>(&to_value("{\"b\":[],\"a\":2}")?)?;
`Value` here is a very vague type name without the namespace information. Can you alias it as `JsonValue` in the use statement?

2023-02-20 10:04 UTC, netrome commented on stacks-js-rs/stacks.ts
> +    readonly vtxindex: number
Edit: Looking at the testnet [sBTC contract](https://github.com/stacks-network/stacks-blockchain/pull/3499/files#diff-42dbc9fe309ad9c61d62ed3518345dcf477e2bba101408726aea8c3f8683a1df), the `txid` is also important here.

2023-02-20 14:15 UTC, igorsyl commented on stacks-js-rs/stacks.ts
> +    readonly vtxindex: number
FYI @netrome source of truth for sBTC contract is [here](https://github.com/Trust-Machines/core-eng/blob/main/sbtc-ops/clarinet/contracts/sbtc-alpha.clar).

2023-02-20 14:18 UTC, netrome commented on stacks-js-rs/stacks.ts
> +    readonly vtxindex: number
Right, thanks that's better. The method signature is the same, so `txid`, `recipient` and `amount` should be enough here. We probably also need to send the coordinator credentials in some format to sign the contract call transactions.

2023-02-20 17:10 UTC, sergey-shandar commented on stacks-js-rs/stacks.ts
> +}
We can restructure internal RPC call as we want, may be in the next PR.

2023-02-21 08:53 UTC, netrome approved these changes

2023-02-22 17:54 UTC, xoloki approved these changes
Lgtm, didn't set any obvious problems in the rust code, but I'm not really qualified to judge the js or ts

2023-02-22 19:29 UTC, sergey-shandar commented
> Lgtm, didn't set any obvious problems in the rust code, but I'm not really qualified to judge the js or ts

I hope, we will get rid of the JS in one of the future PR and replace it with Rust code.

2023-02-22 19:30 UTC, donpdonp approved these changes
.rs traits - great, is actually a start on stacks.rs with a paticular (deno) implementation.
.js files - had a call with sergey as to why this layer is needed
stacks.js/deno - I'd wager stack.rs implementation is equal to the overhead of this approach.

the code here looks great for what its supposed to do.

2023-02-22 19:32 UTC, merged

2023-02-22 21:16 UTC, igorsyl commented
> .rs traits - great, is actually a start on stacks.rs with a paticular (deno) implementation. .js files - had a call with sergey as to why this layer is needed stacks.js/deno - I'd wager stack.rs implementation is equal to the overhead of this approach.
> 
> the code here looks great for what its supposed to do.

I love the push back @donpdonp ! Let's keep watching over each other!